fix: improve trie format for git storage (#3430)
* fix: Document TrieXv3 format.
* dev: Add TrieXv4 format.
* chore: fix jest launch program.  
   Fixes:

   ```
   basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
             ^^^^^^^
   SyntaxError: missing ) after argument list
   ```
* Add line breaks to v3
* Add line break for single letters as well.